#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Set the git root folder path
GIT_ROOT=$(git rev-parse --show-toplevel)

# Define the rebase and merge paths
REBASE_PATH="$GIT_ROOT/.git/rebase-merge"
MERGE_PATH="$GIT_ROOT/.git/MERGE_HEAD"

# Check if the rebase or merge path exists.
# If they don't, it's a normal commit and we can run the pre-commit hook
if [ -f "$REBASE_PATH" ] || [ -f "$MERGE_PATH" ]; then
  echo "Skipping Husky pre-commit hook: We are in the middle of a rebase or merge."
else
  echo "Running Husky pre-commit hook: Formatting affected files"
  npx lint-staged
fi
